'use strict';

// Muscle group pairings with wger.de category IDs
// wger categories: 8=Arms 9=Legs 10=Abs 11=Chest 12=Back 13=Shoulders 14=Calves
const WORKOUT_TYPES = [
  {
    id: 'chest-triceps',
    name: 'Chest & Triceps',
    emoji: '🏋️',
    muscles: ['Chest', 'Triceps'],
    description: 'Push day — upper body pressing power',
    color: '#C0392B',
    gradient: 'linear-gradient(135deg, #96281B 0%, #C0392B 100%)',
    icons: ['🏋️', '💪', '🔥', '⚡'],
    // fetch 5 chest + 3 arm exercises
    categories: [{ id: 11, count: 5 }, { id: 8, count: 3 }],
  },
  {
    id: 'back-biceps',
    name: 'Back & Biceps',
    emoji: '🦾',
    muscles: ['Back', 'Biceps'],
    description: 'Pull day — width and thickness',
    color: '#2471A3',
    gradient: 'linear-gradient(135deg, #1A5276 0%, #2471A3 100%)',
    icons: ['🦾', '💪', '🔥', '⚡'],
    categories: [{ id: 12, count: 5 }, { id: 8, count: 3 }],
  },
  {
    id: 'shoulders-traps',
    name: 'Shoulders & Traps',
    emoji: '🦅',
    muscles: ['Shoulders', 'Trapezius'],
    description: 'Upper body width and posture',
    color: '#7D3C98',
    gradient: 'linear-gradient(135deg, #5B2C6F 0%, #7D3C98 100%)',
    icons: ['🦅', '💪', '🔥', '⚡'],
    categories: [{ id: 13, count: 8 }],
  },
  {
    id: 'legs-quads',
    name: 'Legs — Quad Focus',
    emoji: '🦵',
    muscles: ['Quadriceps', 'Glutes'],
    description: 'Quad-dominant strength and size',
    color: '#1D8348',
    gradient: 'linear-gradient(135deg, #145A32 0%, #1D8348 100%)',
    icons: ['🦵', '🔥', '⚡', '💪'],
    categories: [{ id: 9, count: 8 }],
  },
  {
    id: 'legs-hamstrings',
    name: 'Legs — Hinge & Calves',
    emoji: '🏃',
    muscles: ['Hamstrings', 'Calves'],
    description: 'Posterior chain and calf development',
    color: '#CA6F1E',
    gradient: 'linear-gradient(135deg, #9A4A0E 0%, #CA6F1E 100%)',
    icons: ['🏃', '⚡', '🔥', '💪'],
    categories: [{ id: 9, count: 5 }, { id: 14, count: 3 }],
  },
  {
    id: 'arms',
    name: 'Arms Day',
    emoji: '💪',
    muscles: ['Biceps', 'Triceps'],
    description: 'Dedicated arm sculpting session',
    color: '#E67E22',
    gradient: 'linear-gradient(135deg, #B7520B 0%, #E67E22 100%)',
    icons: ['💪', '🔥', '⚡', '🦾'],
    categories: [{ id: 8, count: 8 }],
  },
  {
    id: 'core',
    name: 'Core & Abs',
    emoji: '🎯',
    muscles: ['Abs', 'Core'],
    description: 'Foundation of every movement',
    color: '#148F77',
    gradient: 'linear-gradient(135deg, #0B6251 0%, #148F77 100%)',
    icons: ['🎯', '⚡', '🔥', '💪'],
    categories: [{ id: 10, count: 8 }],
  },
];

// Fallback exercises per category if API is unreachable
const FALLBACK = {
  11: [ // Chest
    { id: 9011, name: 'Barbell Bench Press',        muscles: 'Pectoralis major', image: null },
    { id: 9012, name: 'Incline Dumbbell Press',      muscles: 'Pectoralis major (upper)', image: null },
    { id: 9013, name: 'Dumbbell Flyes',              muscles: 'Pectoralis major', image: null },
    { id: 9014, name: 'Cable Crossover',             muscles: 'Pectoralis major', image: null },
    { id: 9015, name: 'Push-Ups',                   muscles: 'Pectoralis major, Triceps', image: null },
    { id: 9016, name: 'Decline Bench Press',         muscles: 'Pectoralis major (lower)', image: null },
  ],
  12: [ // Back
    { id: 9021, name: 'Barbell Row',                muscles: 'Latissimus dorsi', image: null },
    { id: 9022, name: 'Pull-Ups',                   muscles: 'Latissimus dorsi, Biceps', image: null },
    { id: 9023, name: 'Seated Cable Row',            muscles: 'Rhomboids, Latissimus dorsi', image: null },
    { id: 9024, name: 'Lat Pulldown',                muscles: 'Latissimus dorsi', image: null },
    { id: 9025, name: 'Deadlift',                   muscles: 'Erector spinae, Glutes', image: null },
    { id: 9026, name: 'T-Bar Row',                  muscles: 'Latissimus dorsi', image: null },
  ],
  13: [ // Shoulders
    { id: 9031, name: 'Barbell Overhead Press',      muscles: 'Deltoid', image: null },
    { id: 9032, name: 'Dumbbell Lateral Raise',      muscles: 'Deltoid (lateral)', image: null },
    { id: 9033, name: 'Dumbbell Shoulder Press',     muscles: 'Deltoid', image: null },
    { id: 9034, name: 'Front Raise',                muscles: 'Deltoid (anterior)', image: null },
    { id: 9035, name: 'Rear Delt Fly',              muscles: 'Deltoid (posterior)', image: null },
    { id: 9036, name: 'Barbell Shrug',              muscles: 'Trapezius', image: null },
    { id: 9037, name: 'Arnold Press',               muscles: 'Deltoid', image: null },
    { id: 9038, name: 'Upright Row',                muscles: 'Deltoid, Trapezius', image: null },
  ],
  9: [ // Legs
    { id: 9041, name: 'Barbell Squat',              muscles: 'Quadriceps, Glutes', image: null },
    { id: 9042, name: 'Leg Press',                  muscles: 'Quadriceps, Glutes', image: null },
    { id: 9043, name: 'Romanian Deadlift',           muscles: 'Hamstrings, Glutes', image: null },
    { id: 9044, name: 'Dumbbell Lunge',             muscles: 'Quadriceps, Glutes', image: null },
    { id: 9045, name: 'Leg Extension',              muscles: 'Quadriceps', image: null },
    { id: 9046, name: 'Lying Leg Curl',             muscles: 'Hamstrings', image: null },
    { id: 9047, name: 'Bulgarian Split Squat',       muscles: 'Quadriceps, Glutes', image: null },
    { id: 9048, name: 'Hack Squat',                 muscles: 'Quadriceps', image: null },
  ],
  14: [ // Calves
    { id: 9051, name: 'Standing Calf Raise',        muscles: 'Gastrocnemius', image: null },
    { id: 9052, name: 'Seated Calf Raise',          muscles: 'Soleus', image: null },
    { id: 9053, name: 'Donkey Calf Raise',          muscles: 'Gastrocnemius', image: null },
  ],
  8: [ // Arms
    { id: 9061, name: 'Barbell Curl',               muscles: 'Biceps brachii', image: null },
    { id: 9062, name: 'Dumbbell Hammer Curl',        muscles: 'Brachialis, Biceps', image: null },
    { id: 9063, name: 'Preacher Curl',              muscles: 'Biceps brachii', image: null },
    { id: 9064, name: 'Tricep Pushdown',            muscles: 'Triceps brachii', image: null },
    { id: 9065, name: 'Skull Crushers',             muscles: 'Triceps brachii', image: null },
    { id: 9066, name: 'Overhead Tricep Extension',  muscles: 'Triceps brachii', image: null },
    { id: 9067, name: 'Dips',                       muscles: 'Triceps, Chest', image: null },
    { id: 9068, name: 'Close-Grip Bench Press',     muscles: 'Triceps brachii', image: null },
  ],
  10: [ // Abs
    { id: 9071, name: 'Crunch',                     muscles: 'Rectus abdominis', image: null },
    { id: 9072, name: 'Plank',                      muscles: 'Core', image: null },
    { id: 9073, name: 'Hanging Leg Raise',          muscles: 'Rectus abdominis, Hip flexors', image: null },
    { id: 9074, name: 'Cable Crunch',               muscles: 'Rectus abdominis', image: null },
    { id: 9075, name: 'Russian Twist',              muscles: 'Obliques', image: null },
    { id: 9076, name: 'Ab Wheel Rollout',           muscles: 'Rectus abdominis', image: null },
    { id: 9077, name: 'Bicycle Crunch',             muscles: 'Obliques, Rectus abdominis', image: null },
    { id: 9078, name: 'Mountain Climbers',          muscles: 'Core, Hip flexors', image: null },
  ],
};
