'use strict';

const LANGUAGES = {
  en: { id: 2,  short: 'en', flag: '🇺🇸', label: 'EN' },
  sq: { id: 21, short: 'sq', flag: '🇦🇱', label: 'SQ' },
  es: { id: 4,  short: 'es', flag: '🇪🇸', label: 'ES' },
};

const UI = {
  en: {
    todaySuggestion: "TODAY'S SUGGESTION",
    muscleStatus:    'MUSCLE STATUS — tap to start',
    workoutHistory:  'WORKOUT HISTORY',
    startWorkout:    '▶ Start Workout',
    viewAgain:       '▶ View Again',
    exercises:       'exercises',
    markComplete:    '✓ Mark Workout Complete',
    completedToday:  '✓ Completed Today',
    doneBadge:       '✓ Done',
    restDay:         'Rest day',
    neverDone:       'Never done',
    today:           'Today',
    yesterday:       'Yesterday',
    dAgo:            'd ago',
    loading:         'Loading exercises…',
    noConnection:    'Could not load exercises — check your connection',
    noHistory:       'No workouts yet',
    noHistoryHint:   'Complete your first workout to see it here',
    home:            'Home',
    workout:         'Workout',
    history:         'History',
    sets:            'Sets',
    reps:            'Reps',
    rest:            'Rest',
    sec:             'sec',
    clearHistory:    'Clear History',
    clearConfirmMsg: 'Clear all workout history?',
    cancel:          'Cancel',
    clearAll:        'Clear All',
  },
  sq: {
    todaySuggestion: 'SUGJERIMI I SOTËM',
    muscleStatus:    'GJENDJA E MUSKUJVE — trokitni për të nisur',
    workoutHistory:  'HISTORIA E STËRVITJES',
    startWorkout:    '▶ Fillo Stërvitjen',
    viewAgain:       '▶ Shiko Përsëri',
    exercises:       'ushtrime',
    markComplete:    '✓ Shëno si të Kryer',
    completedToday:  '✓ Kryer Sot',
    doneBadge:       '✓ Kryer',
    restDay:         'Ditë pushimi',
    neverDone:       'Kurrë nuk është bërë',
    today:           'Sot',
    yesterday:       'Dje',
    dAgo:            'ditë më parë',
    loading:         'Duke ngarkuar ushtrimet…',
    noConnection:    'Nuk mund të ngarkohen ushtrimet — kontrolloni lidhjen',
    noHistory:       'Ende pa stërvitje',
    noHistoryHint:   'Kryeni stërvitjen e parë për ta parë këtu',
    home:            'Kryefaqja',
    workout:         'Stërvitje',
    history:         'Historia',
    sets:            'Sete',
    reps:            'Rep',
    rest:            'Pushim',
    sec:             'sek',
    clearHistory:    'Pastro Historinë',
    clearConfirmMsg: 'Fshi të gjithë historinë e stërvitjes?',
    cancel:          'Anulo',
    clearAll:        'Fshi të Gjitha',
  },
  es: {
    todaySuggestion: 'SUGERENCIA DE HOY',
    muscleStatus:    'ESTADO MUSCULAR — toca para empezar',
    workoutHistory:  'HISTORIAL',
    startWorkout:    '▶ Iniciar Entrenamiento',
    viewAgain:       '▶ Ver de Nuevo',
    exercises:       'ejercicios',
    markComplete:    '✓ Marcar como Completado',
    completedToday:  '✓ Completado Hoy',
    doneBadge:       '✓ Hecho',
    restDay:         'Día de descanso',
    neverDone:       'Nunca realizado',
    today:           'Hoy',
    yesterday:       'Ayer',
    dAgo:            'd atrás',
    loading:         'Cargando ejercicios…',
    noConnection:    'No se pudieron cargar los ejercicios — revisa tu conexión',
    noHistory:       'Sin entrenamientos aún',
    noHistoryHint:   'Completa tu primer entrenamiento para verlo aquí',
    home:            'Inicio',
    workout:         'Entrenamiento',
    history:         'Historial',
    sets:            'Series',
    reps:            'Reps',
    rest:            'Descanso',
    sec:             'seg',
    clearHistory:    'Borrar Historial',
    clearConfirmMsg: '¿Borrar todo el historial de entrenamientos?',
    cancel:          'Cancelar',
    clearAll:        'Borrar Todo',
  },
};

// Base URL for free exercise images (yuhonas/free-exercise-db, MIT licence)
const IMG = (name, idx = 0) =>
  `https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/${name}/${idx}.jpg`;

// wger category IDs: 8=Arms 9=Legs 10=Abs 11=Chest 12=Back 13=Shoulders 14=Calves
const WORKOUT_TYPES = [
  {
    id: 'chest-triceps',
    emoji: '🏋️',
    color: '#C0392B',
    gradient: 'linear-gradient(135deg, #96281B 0%, #C0392B 100%)',
    icons: ['🏋️', '💪', '🔥', '⚡'],
    categories: [{ id: 11, count: 5 }, { id: 8, count: 3 }],
    defaultProto: { sets: 4, reps: '8-12', rest: 75 },
    names:   { en: 'Chest & Triceps',      sq: 'Gjoksi & Tricepsi',          es: 'Pecho & Tríceps' },
    descs:   { en: 'Push day — upper body pressing power', sq: 'Ditë shtytëse — fuqi e pjesës së sipërme', es: 'Día de empuje — fuerza en la parte superior' },
    muscles: { en: ['Chest','Triceps'],     sq: ['Gjoksi','Tricepsi'],         es: ['Pecho','Tríceps'] },
  },
  {
    id: 'back-biceps',
    emoji: '🦾',
    color: '#2471A3',
    gradient: 'linear-gradient(135deg, #1A5276 0%, #2471A3 100%)',
    icons: ['🦾', '💪', '🔥', '⚡'],
    categories: [{ id: 12, count: 5 }, { id: 8, count: 3 }],
    defaultProto: { sets: 4, reps: '8-12', rest: 75 },
    names:   { en: 'Back & Biceps',         sq: 'Shpina & Bicepsi',            es: 'Espalda & Bíceps' },
    descs:   { en: 'Pull day — width and thickness',     sq: 'Ditë tërheqëse — gjerësi dhe trashësi', es: 'Día de jalón — anchura y grosor' },
    muscles: { en: ['Back','Biceps'],        sq: ['Shpina','Bicepsi'],           es: ['Espalda','Bíceps'] },
  },
  {
    id: 'shoulders-traps',
    emoji: '🦅',
    color: '#7D3C98',
    gradient: 'linear-gradient(135deg, #5B2C6F 0%, #7D3C98 100%)',
    icons: ['🦅', '💪', '🔥', '⚡'],
    categories: [{ id: 13, count: 8 }],
    defaultProto: { sets: 4, reps: '10-15', rest: 60 },
    names:   { en: 'Shoulders & Traps',     sq: 'Supet & Trapezoidi',           es: 'Hombros & Trapecios' },
    descs:   { en: 'Upper body width and posture',       sq: 'Gjerësia e pjesës së sipërme dhe qëndrimi', es: 'Anchura en la parte superior y postura' },
    muscles: { en: ['Shoulders','Traps'],    sq: ['Supet','Trapezoidi'],          es: ['Hombros','Trapecios'] },
  },
  {
    id: 'legs-quads',
    emoji: '🦵',
    color: '#1D8348',
    gradient: 'linear-gradient(135deg, #145A32 0%, #1D8348 100%)',
    icons: ['🦵', '🔥', '⚡', '💪'],
    categories: [{ id: 9, count: 8 }],
    defaultProto: { sets: 4, reps: '8-12', rest: 90 },
    names:   { en: 'Legs — Quad Focus',     sq: 'Këmbët — Fokus Kuadricepsi',   es: 'Piernas — Énfasis en Cuádriceps' },
    descs:   { en: 'Quad-dominant strength and size',   sq: 'Fuqi dhe vëllim i kuadricepsit',          es: 'Fuerza y volumen de cuádriceps' },
    muscles: { en: ['Quadriceps','Glutes'], sq: ['Kuadricepsi','Gluteusi'],      es: ['Cuádriceps','Glúteos'] },
  },
  {
    id: 'legs-hamstrings',
    emoji: '🏃',
    color: '#CA6F1E',
    gradient: 'linear-gradient(135deg, #9A4A0E 0%, #CA6F1E 100%)',
    icons: ['🏃', '⚡', '🔥', '💪'],
    categories: [{ id: 9, count: 5 }, { id: 14, count: 3 }],
    defaultProto: { sets: 3, reps: '10-15', rest: 60 },
    names:   { en: 'Legs — Hinge & Calves', sq: 'Këmbët — Panxha & Viçat',      es: 'Piernas — Bisagra & Pantorrillas' },
    descs:   { en: 'Posterior chain and calf development', sq: 'Zinxhiri i pasëm dhe zhvillimi i viçave', es: 'Cadena posterior y desarrollo de pantorrillas' },
    muscles: { en: ['Hamstrings','Calves'], sq: ['Panxhat','Viçat'],             es: ['Isquiotibiales','Pantorrillas'] },
  },
  {
    id: 'arms',
    emoji: '💪',
    color: '#E67E22',
    gradient: 'linear-gradient(135deg, #B7520B 0%, #E67E22 100%)',
    icons: ['💪', '🔥', '⚡', '🦾'],
    categories: [{ id: 8, count: 8 }],
    defaultProto: { sets: 3, reps: '10-15', rest: 60 },
    names:   { en: 'Arms Day',              sq: 'Dita e Krahëve',                es: 'Día de Brazos' },
    descs:   { en: 'Dedicated arm sculpting session',   sq: 'Seancë e dedikuar për krahët',            es: 'Sesión dedicada a los brazos' },
    muscles: { en: ['Biceps','Triceps'],     sq: ['Bicepsi','Tricepsi'],          es: ['Bíceps','Tríceps'] },
  },
  {
    id: 'core',
    emoji: '🎯',
    color: '#148F77',
    gradient: 'linear-gradient(135deg, #0B6251 0%, #148F77 100%)',
    icons: ['🎯', '⚡', '🔥', '💪'],
    categories: [{ id: 10, count: 8 }],
    defaultProto: { sets: 3, reps: '15-20', rest: 45 },
    names:   { en: 'Core & Abs',            sq: 'Beli & Abdominali',             es: 'Core & Abdominales' },
    descs:   { en: 'Foundation of every movement',     sq: 'Themeli i çdo lëvizjeje',                 es: 'Base de todo movimiento' },
    muscles: { en: ['Abs','Core'],           sq: ['Abdominali','Beli'],           es: ['Abdominales','Core'] },
  },
];

// Hardcoded fallback exercises — shown when the wger API is unreachable.
// Every image URL verified 200 against yuhonas/free-exercise-db (MIT licence).
// Pools are 12-15 exercises per category so per-card refresh always has spares.
// proto = { sets, reps, rest (seconds) }
const FALLBACK = {
  11: [ // Chest — 12 exercises
    { id: 9101, names: { en: 'Barbell Bench Press',        es: 'Press de Banca con Barra',          sq: 'Shtytje me Stol me Barre'         }, muscles: 'Chest',          image: IMG('Barbell_Bench_Press_-_Medium_Grip'),         proto: { sets: 4, reps: '6-10',  rest: 90  } },
    { id: 9102, names: { en: 'Incline Dumbbell Press',     es: 'Press Inclinado con Mancuernas',    sq: 'Shtytje e Pjerrët me Pesha'       }, muscles: 'Upper chest',    image: IMG('Incline_Dumbbell_Press'),                    proto: { sets: 3, reps: '10-12', rest: 75  } },
    { id: 9103, names: { en: 'Dumbbell Flyes',             es: 'Aperturas con Mancuernas',          sq: 'Hapja me Pesha'                   }, muscles: 'Chest',          image: IMG('Dumbbell_Flyes'),                            proto: { sets: 3, reps: '12-15', rest: 60  } },
    { id: 9104, names: { en: 'Cable Crossover',            es: 'Cruce de Poleas',                   sq: 'Kryqëzim me Kavo'                 }, muscles: 'Chest',          image: IMG('Cable_Crossover'),                           proto: { sets: 3, reps: '12-15', rest: 60  } },
    { id: 9105, names: { en: 'Push-Ups',                   es: 'Flexiones',                         sq: 'Shtytje'                          }, muscles: 'Chest, Triceps', image: IMG('Pushups'),                                   proto: { sets: 3, reps: '15-20', rest: 45  } },
    { id: 9106, names: { en: 'Decline Bench Press',        es: 'Press Declinado',                   sq: 'Shtytje e Zbritur me Stol'        }, muscles: 'Lower chest',    image: IMG('Decline_Barbell_Bench_Press'),               proto: { sets: 3, reps: '10-12', rest: 75  } },
    { id: 9107, names: { en: 'Incline Barbell Press',      es: 'Press Inclinado con Barra',         sq: 'Shtytje e Pjerrët me Barre'       }, muscles: 'Upper chest',    image: IMG('Barbell_Incline_Bench_Press_-_Medium_Grip'), proto: { sets: 4, reps: '8-10',  rest: 75  } },
    { id: 9108, names: { en: 'Dumbbell Bench Press',       es: 'Press de Banca con Mancuernas',     sq: 'Shtytje me Stol me Pesha'         }, muscles: 'Chest',          image: IMG('Dumbbell_Bench_Press'),                      proto: { sets: 3, reps: '10-12', rest: 75  } },
    { id: 9109, names: { en: 'Low Cable Crossover',        es: 'Cruce de Poleas Bajo',              sq: 'Kryqëzim i Ulët me Kavo'          }, muscles: 'Lower chest',    image: IMG('Low_Cable_Crossover'),                       proto: { sets: 3, reps: '12-15', rest: 60  } },
    { id: 9110, names: { en: 'Dumbbell Pullover',          es: 'Pullover con Mancuerna',            sq: 'Tërheqje mbi Kokë me Peshë'       }, muscles: 'Chest, Lats',    image: IMG('Bent-Arm_Dumbbell_Pullover'),                proto: { sets: 3, reps: '12-15', rest: 60  } },
    { id: 9111, names: { en: 'Bodyweight Flyes',           es: 'Aperturas con Peso Corporal',       sq: 'Hapja me Peshën e Trupit'         }, muscles: 'Chest',          image: IMG('Bodyweight_Flyes'),                          proto: { sets: 3, reps: '10-15', rest: 60  } },
    { id: 9112, names: { en: 'Guillotine Bench Press',     es: 'Press de Cuello',                   sq: 'Shtytje Gjilpërë'                 }, muscles: 'Upper chest',    image: IMG('Barbell_Guillotine_Bench_Press'),            proto: { sets: 3, reps: '10-12', rest: 75  } },
  ],
  12: [ // Back — 12 exercises
    { id: 9121, names: { en: 'Bent Over Row',              es: 'Remo con Barra',                    sq: 'Remo me Barre'                    }, muscles: 'Lats, Rhomboids',     image: IMG('Bent_Over_Barbell_Row'),                 proto: { sets: 4, reps: '6-10',  rest: 90  } },
    { id: 9122, names: { en: 'Chin-Up',                    es: 'Dominada Supina',                   sq: 'Ngjitje me Kapje Supine'          }, muscles: 'Lats, Biceps',        image: IMG('Chin-Up'),                               proto: { sets: 4, reps: '6-12',  rest: 90  } },
    { id: 9123, names: { en: 'Dumbbell Row',               es: 'Remo con Mancuernas',               sq: 'Remo me Pesha'                    }, muscles: 'Lats, Rhomboids',     image: IMG('Bent_Over_Two-Dumbbell_Row'),             proto: { sets: 3, reps: '10-12', rest: 60  } },
    { id: 9124, names: { en: 'Lat Pulldown',               es: 'Jalón al Pecho',                    sq: 'Tërheqje Lat'                     }, muscles: 'Latissimus dorsi',    image: IMG('Wide-Grip_Lat_Pulldown'),                 proto: { sets: 4, reps: '10-12', rest: 60  } },
    { id: 9125, names: { en: 'Deadlift',                   es: 'Peso Muerto',                       sq: 'Ngritja e Rëndë'                  }, muscles: 'Lats, Erector spine', image: IMG('Barbell_Deadlift'),                       proto: { sets: 4, reps: '4-6',   rest: 120 } },
    { id: 9126, names: { en: 'T-Bar Row',                  es: 'Remo en T',                         sq: 'Remo T-Bar'                       }, muscles: 'Latissimus dorsi',    image: IMG('T-Bar_Row_with_Handle'),                  proto: { sets: 3, reps: '10-12', rest: 75  } },
    { id: 9127, names: { en: 'Incline Dumbbell Row',       es: 'Remo Inclinado con Mancuernas',     sq: 'Remo i Pjerrët me Pesha'          }, muscles: 'Rhomboids, Lats',     image: IMG('Dumbbell_Incline_Row'),                   proto: { sets: 3, reps: '12-15', rest: 60  } },
    { id: 9128, names: { en: 'Rear Delt Row',              es: 'Remo Deltoides Posterior',          sq: 'Remo i Deltoidit të Pasëm'        }, muscles: 'Rear delts, Traps',   image: IMG('Barbell_Rear_Delt_Row'),                  proto: { sets: 3, reps: '12-15', rest: 60  } },
    { id: 9129, names: { en: 'Inverted Row',               es: 'Remo Invertido',                    sq: 'Remo i Përmbysur'                 }, muscles: 'Lats, Rhomboids',     image: IMG('Bodyweight_Mid_Row'),                     proto: { sets: 3, reps: '12-15', rest: 60  } },
    { id: 9130, names: { en: 'Renegade Row',               es: 'Remo Renegado',                     sq: 'Remo Renegat'                     }, muscles: 'Lats, Core',          image: IMG('Alternating_Renegade_Row'),               proto: { sets: 3, reps: '8/side', rest: 75  } },
    { id: 9131, names: { en: 'Behind-Neck Pulldown',       es: 'Jalón Tras Nuca',                   sq: 'Tërheqje pas Koke'                }, muscles: 'Latissimus dorsi',    image: IMG('Wide-Grip_Pulldown_Behind_The_Neck'),     proto: { sets: 3, reps: '10-12', rest: 60  } },
    { id: 9132, names: { en: 'One-Arm Bar Row',            es: 'Remo Unilateral con Barra',         sq: 'Remo Njëkrahor me Barre'          }, muscles: 'Lats',                image: IMG('Bent_Over_One-Arm_Long_Bar_Row'),         proto: { sets: 3, reps: '10-12', rest: 60  } },
  ],
  13: [ // Shoulders & Traps — 12 exercises
    { id: 9141, names: { en: 'Overhead Press',             es: 'Press Militar con Barra',           sq: 'Shtytje mbi Kokë me Barre'        }, muscles: 'Deltoid',             image: IMG('Barbell_Shoulder_Press'),                 proto: { sets: 4, reps: '6-10',  rest: 90  } },
    { id: 9142, names: { en: 'Lateral Raise',              es: 'Elevaciones Laterales',             sq: 'Ngritje Anësore'                  }, muscles: 'Deltoid (lateral)',    image: IMG('Side_Lateral_Raise'),                     proto: { sets: 4, reps: '12-15', rest: 45  } },
    { id: 9143, names: { en: 'Dumbbell Shoulder Press',    es: 'Press de Hombros con Mancuernas',   sq: 'Shtytje Supesh me Pesha'          }, muscles: 'Deltoid',             image: IMG('Dumbbell_Shoulder_Press'),                proto: { sets: 4, reps: '10-12', rest: 75  } },
    { id: 9144, names: { en: 'Alternating Front Raise',    es: 'Elevación Frontal Alterna',         sq: 'Ngritje Frontale Alternative'     }, muscles: 'Deltoid (anterior)',   image: IMG('Alternating_Deltoid_Raise'),              proto: { sets: 3, reps: '12-15', rest: 45  } },
    { id: 9145, names: { en: 'Rear Delt Fly',              es: 'Vuelo Deltoides Posterior',         sq: 'Hapja e Deltoidit të Pasëm'       }, muscles: 'Deltoid (posterior)', image: IMG('Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench'), proto: { sets: 3, reps: '12-15', rest: 45  } },
    { id: 9146, names: { en: 'Barbell Shrug',              es: 'Encogimiento con Barra',            sq: 'Ngritje Supesh me Barre'          }, muscles: 'Trapezius',           image: IMG('Barbell_Shrug'),                          proto: { sets: 4, reps: '12-15', rest: 60  } },
    { id: 9147, names: { en: 'Arnold Press',               es: 'Press Arnold',                      sq: 'Shtytje Arnold'                   }, muscles: 'Deltoid (all heads)', image: IMG('Arnold_Dumbbell_Press'),                  proto: { sets: 3, reps: '10-12', rest: 60  } },
    { id: 9148, names: { en: 'Upright Row',                es: 'Remo al Mentón',                    sq: 'Remo Vertikal'                    }, muscles: 'Deltoid, Trapezius',  image: IMG('Smith_Machine_Upright_Row'),              proto: { sets: 3, reps: '10-12', rest: 60  } },
    { id: 9149, names: { en: 'Incline Shoulder Raise',     es: 'Elevación de Hombros Inclinado',    sq: 'Ngritje Supe e Pjerrët'           }, muscles: 'Deltoid (anterior)',   image: IMG('Barbell_Incline_Shoulder_Raise'),         proto: { sets: 3, reps: '12-15', rest: 45  } },
    { id: 9150, names: { en: 'Cable Shoulder Press',       es: 'Press de Hombros en Cable',         sq: 'Shtytje Supesh me Kavo'           }, muscles: 'Deltoid',             image: IMG('Alternating_Cable_Shoulder_Press'),       proto: { sets: 3, reps: '12-15', rest: 60  } },
    { id: 9151, names: { en: 'Kettlebell Press',           es: 'Press con Kettlebell',              sq: 'Shtytje me Kettle'                }, muscles: 'Deltoid',             image: IMG('Alternating_Kettlebell_Press'),           proto: { sets: 3, reps: '10-12', rest: 60  } },
    { id: 9152, names: { en: 'Shrug Behind Back',          es: 'Encogimiento Detrás de la Espalda', sq: 'Ngritje Supesh pas Shpine'        }, muscles: 'Trapezius',           image: IMG('Barbell_Shrug_Behind_The_Back'),          proto: { sets: 3, reps: '12-15', rest: 60  } },
  ],
  9: [ // Legs — 15 exercises
    { id: 9161, names: { en: 'Barbell Squat',              es: 'Sentadilla con Barra',              sq: 'Ulje-Ngritje me Barre'            }, muscles: 'Quads, Glutes',       image: IMG('Barbell_Full_Squat'),                     proto: { sets: 4, reps: '6-10',  rest: 120 } },
    { id: 9162, names: { en: 'Leg Press',                  es: 'Prensa de Piernas',                 sq: 'Shtytje Këmbësh'                  }, muscles: 'Quads, Glutes',       image: IMG('Leg_Press'),                              proto: { sets: 4, reps: '10-12', rest: 90  } },
    { id: 9163, names: { en: 'Romanian Deadlift',          es: 'Peso Muerto Rumano',                sq: 'Ngritje Rumune'                   }, muscles: 'Hamstrings, Glutes',  image: IMG('Romanian_Deadlift'),                      proto: { sets: 4, reps: '8-10',  rest: 90  } },
    { id: 9164, names: { en: 'Dumbbell Lunge',             es: 'Zancadas con Mancuernas',           sq: 'Hap-Gjuri me Pesha'               }, muscles: 'Quads, Glutes',       image: IMG('Dumbbell_Lunges'),                        proto: { sets: 3, reps: '12/leg', rest: 60  } },
    { id: 9165, names: { en: 'Leg Extension',              es: 'Extensión de Cuádriceps',           sq: 'Shtrirje e Kuadricepsit'          }, muscles: 'Quadriceps',          image: IMG('Leg_Extensions'),                         proto: { sets: 3, reps: '12-15', rest: 60  } },
    { id: 9166, names: { en: 'Lying Leg Curl',             es: 'Curl Femoral Tumbado',              sq: 'Tkurrje Këmbe të Shtrirë'         }, muscles: 'Hamstrings',          image: IMG('Lying_Leg_Curls'),                        proto: { sets: 3, reps: '12-15', rest: 60  } },
    { id: 9167, names: { en: 'Hack Squat',                 es: 'Sentadilla Hack',                   sq: 'Squat Hack'                       }, muscles: 'Quadriceps',          image: IMG('Hack_Squat'),                             proto: { sets: 4, reps: '10-12', rest: 90  } },
    { id: 9168, names: { en: 'Goblet Squat',               es: 'Sentadilla Goblet',                 sq: 'Squat Goblet'                     }, muscles: 'Quads, Glutes',       image: IMG('Goblet_Squat'),                           proto: { sets: 3, reps: '12-15', rest: 60  } },
    { id: 9169, names: { en: 'Box Squat',                  es: 'Sentadilla en Caja',                sq: 'Squat në Kuti'                    }, muscles: 'Quads, Glutes',       image: IMG('Box_Squat'),                              proto: { sets: 4, reps: '6-10',  rest: 90  } },
    { id: 9170, names: { en: 'Sumo Deadlift',              es: 'Peso Muerto Sumo',                  sq: 'Ngritje e Rëndë Sumo'             }, muscles: 'Hamstrings, Glutes',  image: IMG('Sumo_Deadlift'),                          proto: { sets: 4, reps: '6-8',   rest: 120 } },
    { id: 9171, names: { en: 'Hip Thrust',                 es: 'Empuje de Cadera con Barra',        sq: 'Shtytje e Ijeve me Barre'         }, muscles: 'Glutes',              image: IMG('Barbell_Hip_Thrust'),                     proto: { sets: 4, reps: '10-12', rest: 75  } },
    { id: 9172, names: { en: 'Seated Leg Curl',            es: 'Curl Femoral Sentado',              sq: 'Tkurrje Këmbe të Ulur'            }, muscles: 'Hamstrings',          image: IMG('Seated_Leg_Curl'),                        proto: { sets: 3, reps: '12-15', rest: 60  } },
    { id: 9173, names: { en: 'Good Morning',               es: 'Buenos Días con Barra',             sq: 'Mirëmëngjes me Barre'             }, muscles: 'Hamstrings, Lower back', image: IMG('Good_Morning'),                         proto: { sets: 3, reps: '10-12', rest: 75  } },
    { id: 9174, names: { en: 'Barbell Lunge',              es: 'Zancada con Barra',                 sq: 'Hap-Gjuri me Barre'               }, muscles: 'Quads, Glutes',       image: IMG('Barbell_Lunge'),                          proto: { sets: 3, reps: '10/leg', rest: 75  } },
    { id: 9175, names: { en: 'Step-Up',                    es: 'Subida al Escalón',                 sq: 'Ngjitje në Shkallë'               }, muscles: 'Quads, Glutes',       image: IMG('Barbell_Step_Ups'),                       proto: { sets: 3, reps: '10/leg', rest: 60  } },
  ],
  14: [ // Calves — 3 exercises
    { id: 9181, names: { en: 'Standing Calf Raise',        es: 'Elevación de Talones de Pie',       sq: 'Ngritje Viçi në Këmbë'            }, muscles: 'Gastrocnemius',       image: IMG('Standing_Calf_Raises'),                   proto: { sets: 4, reps: '15-20', rest: 45  } },
    { id: 9182, names: { en: 'Seated Calf Raise',          es: 'Elevación de Talones Sentado',      sq: 'Ngritje Viçi të Ulur'             }, muscles: 'Soleus',              image: IMG('Barbell_Seated_Calf_Raise'),              proto: { sets: 4, reps: '15-20', rest: 45  } },
    { id: 9183, names: { en: 'Donkey Calf Raise',          es: 'Elevación de Talones tipo Burro',   sq: 'Ngritje Viçi Gomar'               }, muscles: 'Gastrocnemius',       image: IMG('Donkey_Calf_Raises'),                     proto: { sets: 3, reps: '15-20', rest: 45  } },
  ],
  8: [ // Arms — 15 exercises (biceps + triceps)
    { id: 9201, names: { en: 'Barbell Curl',               es: 'Curl con Barra',                    sq: 'Tkurrje me Barre'                 }, muscles: 'Biceps',              image: IMG('Barbell_Curl'),                           proto: { sets: 4, reps: '10-12', rest: 60  } },
    { id: 9202, names: { en: 'Hammer Curl',                es: 'Curl Martillo',                     sq: 'Tkurrje Çekiç'                    }, muscles: 'Brachialis, Biceps',  image: IMG('Hammer_Curls'),                           proto: { sets: 3, reps: '12-15', rest: 45  } },
    { id: 9203, names: { en: 'Preacher Curl',              es: 'Curl en Banco Scott',               sq: 'Tkurrje Scott'                    }, muscles: 'Biceps',              image: IMG('Preacher_Curl'),                          proto: { sets: 3, reps: '10-12', rest: 60  } },
    { id: 9204, names: { en: 'Concentration Curl',         es: 'Curl de Concentración',             sq: 'Tkurrje Koncentrimi'              }, muscles: 'Biceps',              image: IMG('Concentration_Curls'),                    proto: { sets: 3, reps: '12-15', rest: 45  } },
    { id: 9205, names: { en: 'Incline Dumbbell Curl',      es: 'Curl Inclinado con Mancuerna',      sq: 'Tkurrje e Pjerrët me Peshë'       }, muscles: 'Biceps (long head)', image: IMG('Incline_Dumbbell_Curl'),                   proto: { sets: 3, reps: '10-12', rest: 60  } },
    { id: 9206, names: { en: 'Alternate Hammer Curl',      es: 'Curl Martillo Alterno',             sq: 'Tkurrje Çekiç Alternative'        }, muscles: 'Brachialis, Biceps',  image: IMG('Alternate_Hammer_Curl'),                  proto: { sets: 3, reps: '12/arm', rest: 45  } },
    { id: 9207, names: { en: 'Alternate Incline Curl',     es: 'Curl Inclinado Alterno',            sq: 'Tkurrje e Pjerrët Alternative'    }, muscles: 'Biceps',              image: IMG('Alternate_Incline_Dumbbell_Curl'),        proto: { sets: 3, reps: '10/arm', rest: 60  } },
    { id: 9208, names: { en: 'Tricep Pushdown',            es: 'Extensión de Tríceps en Polea',     sq: 'Shtytje Tricepsi me Kavo'         }, muscles: 'Triceps',             image: IMG('Triceps_Pushdown'),                       proto: { sets: 4, reps: '12-15', rest: 45  } },
    { id: 9209, names: { en: 'Skull Crushers',             es: 'Rompe Cráneos',                     sq: 'Shtrirje Tricepsi'                }, muscles: 'Triceps',             image: IMG('Lying_Triceps_Press'),                    proto: { sets: 3, reps: '10-12', rest: 60  } },
    { id: 9210, names: { en: 'EZ-Bar Skullcrusher',        es: 'Rompe Cráneos con Barra EZ',        sq: 'Shtrirje Tricepsi me Barre EZ'    }, muscles: 'Triceps',             image: IMG('EZ-Bar_Skullcrusher'),                    proto: { sets: 3, reps: '10-12', rest: 60  } },
    { id: 9211, names: { en: 'Seated Triceps Press',       es: 'Extensión Tríceps Sentado',         sq: 'Shtrirje Tricepsi të Ulur'        }, muscles: 'Triceps',             image: IMG('Seated_Triceps_Press'),                   proto: { sets: 3, reps: '12-15', rest: 45  } },
    { id: 9212, names: { en: 'Tricep Dips',                es: 'Fondos en Paralelas',               sq: 'Ulje-Ngritje në Paralele'         }, muscles: 'Triceps, Chest',      image: IMG('Dips_-_Triceps_Version'),                 proto: { sets: 3, reps: '8-15',  rest: 60  } },
    { id: 9213, names: { en: 'Close-Grip Bench Press',     es: 'Press Banca Agarre Cerrado',        sq: 'Shtytje me Kapur Ngushtë'         }, muscles: 'Triceps',             image: IMG('Close-Grip_Barbell_Bench_Press'),         proto: { sets: 3, reps: '10-12', rest: 75  } },
    { id: 9214, names: { en: 'Bench Dips',                 es: 'Fondos en Banco',                   sq: 'Ulje-Ngritje në Bankë'            }, muscles: 'Triceps',             image: IMG('Bench_Dips'),                             proto: { sets: 3, reps: '12-15', rest: 45  } },
    { id: 9215, names: { en: 'Tricep Kickback',            es: 'Patada de Tríceps',                 sq: 'Zgjatje Tricepsi'                 }, muscles: 'Triceps',             image: IMG('Tricep_Dumbbell_Kickback'),               proto: { sets: 3, reps: '12-15', rest: 45  } },
  ],
  10: [ // Abs — 12 exercises
    { id: 9221, names: { en: 'Decline Crunch',             es: 'Crunch en Banco Declinado',         sq: 'Kërthizë e Zbritur'               }, muscles: 'Rectus abdominis',    image: IMG('Decline_Crunch'),                         proto: { sets: 3, reps: '20-25', rest: 30  } },
    { id: 9222, names: { en: 'Plank',                      es: 'Plancha',                           sq: 'Pllakë'                           }, muscles: 'Core',                image: IMG('Plank'),                                  proto: { sets: 3, reps: '45 sec', rest: 30  } },
    { id: 9223, names: { en: 'Hanging Leg Raise',          es: 'Elevación de Piernas Colgado',      sq: 'Ngritje Këmbësh të Varur'         }, muscles: 'Lower abs, Hip flex', image: IMG('Hanging_Leg_Raise'),                      proto: { sets: 3, reps: '12-15', rest: 45  } },
    { id: 9224, names: { en: 'Cable Crunch',               es: 'Crunch en Polea',                   sq: 'Kërthizë me Kavo'                 }, muscles: 'Rectus abdominis',    image: IMG('Cable_Crunch'),                           proto: { sets: 3, reps: '15-20', rest: 45  } },
    { id: 9225, names: { en: 'Russian Twist',              es: 'Giro Ruso',                         sq: 'Rrotullim Rus'                    }, muscles: 'Obliques',            image: IMG('Russian_Twist'),                          proto: { sets: 3, reps: '20/side', rest: 30  } },
    { id: 9226, names: { en: 'Ab Wheel Rollout',           es: 'Rueda Abdominal',                   sq: 'Rrota e Abdominalit'              }, muscles: 'Rectus abdominis',    image: IMG('Ab_Roller'),                              proto: { sets: 3, reps: '10-12', rest: 60  } },
    { id: 9227, names: { en: 'Bicycle Crunch',             es: 'Crunch de Bicicleta',               sq: 'Kërthizë Biçiklete'               }, muscles: 'Obliques, Abs',       image: IMG('Air_Bike'),                               proto: { sets: 3, reps: '20/side', rest: 30  } },
    { id: 9228, names: { en: 'Mountain Climbers',          es: 'Escaladores de Montaña',            sq: 'Ngjitës Mali'                     }, muscles: 'Core, Hip flexors',   image: IMG('Mountain_Climbers'),                      proto: { sets: 3, reps: '30 sec', rest: 30  } },
    { id: 9229, names: { en: 'Exercise Ball Crunch',       es: 'Crunch en Pelota',                  sq: 'Kërthizë me Top'                  }, muscles: 'Rectus abdominis',    image: IMG('Exercise_Ball_Crunch'),                   proto: { sets: 3, reps: '20-25', rest: 30  } },
    { id: 9230, names: { en: '3/4 Sit-Up',                 es: 'Sit-Up 3/4',                        sq: 'Ulje-Ngritje ¾'                   }, muscles: 'Rectus abdominis',    image: IMG('3_4_Sit-Up'),                             proto: { sets: 3, reps: '15-20', rest: 30  } },
    { id: 9231, names: { en: 'Barbell Ab Rollout',         es: 'Rueda Abdominal con Barra',         sq: 'Rrota Abdominale me Barre'        }, muscles: 'Rectus abdominis',    image: IMG('Barbell_Ab_Rollout'),                     proto: { sets: 3, reps: '8-12',  rest: 60  } },
    { id: 9232, names: { en: 'Bent-Knee Hip Raise',        es: 'Elevación de Cadera Rodillas Dobladas', sq: 'Ngritje Ijesh me Gjunj të Përkulur' }, muscles: 'Lower abs',    image: IMG('Bent-Knee_Hip_Raise'),                    proto: { sets: 3, reps: '15-20', rest: 30  } },
  ],
};
