'use strict';

// Language config — IDs match wger.de /api/v2/language/
const LANGUAGES = {
  en: { id: 2,  short: 'en', flag: '🇺🇸', label: 'EN' },
  sq: { id: 21, short: 'sq', flag: '🇦🇱', label: 'SQ' }, // Albanian; falls back to EN if unavailable
  es: { id: 4,  short: 'es', flag: '🇪🇸', label: 'ES' },
};

// All UI copy in the three languages
const UI = {
  en: {
    todaySuggestion:    "TODAY'S SUGGESTION",
    muscleStatus:       'MUSCLE STATUS',
    workoutHistory:     'WORKOUT HISTORY',
    startWorkout:       '▶ Start Workout',
    viewAgain:          '▶ View Again',
    exercises:          'exercises',
    markComplete:       '✓ Mark Workout Complete',
    completedToday:     '✓ Completed Today',
    doneBadge:          '✓ Done',
    restDay:            'Rest day',
    neverDone:          'Never done',
    today:              'Today',
    yesterday:          'Yesterday',
    dAgo:               'd ago',
    loading:            'Loading exercises…',
    noConnection:       'Could not load exercises — check your connection',
    noHistory:          'No workouts yet',
    noHistoryHint:      'Complete your first workout to see it here',
    home:               'Home',
    workout:            'Workout',
    history:            'History',
  },
  sq: {
    todaySuggestion:    'SUGJERIMI I SOTËM',
    muscleStatus:       'GJENDJA E MUSKUJVE',
    workoutHistory:     'HISTORIA E STËRVITJES',
    startWorkout:       '▶ Fillo Stërvitjen',
    viewAgain:          '▶ Shiko Përsëri',
    exercises:          'ushtrime',
    markComplete:       '✓ Shëno si të Kryer',
    completedToday:     '✓ Kryer Sot',
    doneBadge:          '✓ Kryer',
    restDay:            'Ditë pushimi',
    neverDone:          'Kurrë nuk është bërë',
    today:              'Sot',
    yesterday:          'Dje',
    dAgo:               'ditë më parë',
    loading:            'Duke ngarkuar ushtrimet…',
    noConnection:       'Nuk mund të ngarkohen ushtrimet — kontrolloni lidhjen',
    noHistory:          'Ende pa stërvitje',
    noHistoryHint:      'Kryeni stërvitjen e parë për ta parë këtu',
    home:               'Kryefaqja',
    workout:            'Stërvitje',
    history:            'Historia',
  },
  es: {
    todaySuggestion:    'SUGERENCIA DE HOY',
    muscleStatus:       'ESTADO MUSCULAR',
    workoutHistory:     'HISTORIAL',
    startWorkout:       '▶ Iniciar Entrenamiento',
    viewAgain:          '▶ Ver de Nuevo',
    exercises:          'ejercicios',
    markComplete:       '✓ Marcar como Completado',
    completedToday:     '✓ Completado Hoy',
    doneBadge:          '✓ Hecho',
    restDay:            'Día de descanso',
    neverDone:          'Nunca realizado',
    today:              'Hoy',
    yesterday:          'Ayer',
    dAgo:               'd atrás',
    loading:            'Cargando ejercicios…',
    noConnection:       'No se pudieron cargar los ejercicios — revisa tu conexión',
    noHistory:          'Sin entrenamientos aún',
    noHistoryHint:      'Completa tu primer entrenamiento para verlo aquí',
    home:               'Inicio',
    workout:            'Entrenamiento',
    history:            'Historial',
  },
};

// Workout type pairings — names/descriptions/muscles in all 3 languages
// wger category IDs: 8=Arms 9=Legs 10=Abs 11=Chest 12=Back 13=Shoulders 14=Calves
const WORKOUT_TYPES = [
  {
    id: 'chest-triceps',
    emoji: '🏋️',
    color: '#C0392B',
    gradient: 'linear-gradient(135deg, #96281B 0%, #C0392B 100%)',
    icons: ['🏋️', '💪', '🔥', '⚡'],
    categories: [{ id: 11, count: 5 }, { id: 8, count: 3 }],
    names:       { en: 'Chest & Triceps',       sq: 'Gjoksi & Tricepsi',         es: 'Pecho & Tríceps' },
    descs:       { en: 'Push day — upper body pressing power', sq: 'Ditë shtytëse — fuqi e pjesës së sipërme', es: 'Día de empuje — fuerza en la parte superior' },
    muscles:     { en: ['Chest','Triceps'],      sq: ['Gjoksi','Tricepsi'],        es: ['Pecho','Tríceps'] },
  },
  {
    id: 'back-biceps',
    emoji: '🦾',
    color: '#2471A3',
    gradient: 'linear-gradient(135deg, #1A5276 0%, #2471A3 100%)',
    icons: ['🦾', '💪', '🔥', '⚡'],
    categories: [{ id: 12, count: 5 }, { id: 8, count: 3 }],
    names:       { en: 'Back & Biceps',          sq: 'Shpina & Bicepsi',           es: 'Espalda & Bíceps' },
    descs:       { en: 'Pull day — width and thickness',      sq: 'Ditë tërheqëse — gjerësi dhe trashësi', es: 'Día de jalón — anchura y grosor' },
    muscles:     { en: ['Back','Biceps'],         sq: ['Shpina','Bicepsi'],          es: ['Espalda','Bíceps'] },
  },
  {
    id: 'shoulders-traps',
    emoji: '🦅',
    color: '#7D3C98',
    gradient: 'linear-gradient(135deg, #5B2C6F 0%, #7D3C98 100%)',
    icons: ['🦅', '💪', '🔥', '⚡'],
    categories: [{ id: 13, count: 8 }],
    names:       { en: 'Shoulders & Traps',      sq: 'Supet & Trapezoidi',          es: 'Hombros & Trapecios' },
    descs:       { en: 'Upper body width and posture',        sq: 'Gjerësia e pjesës së sipërme dhe qëndrimi', es: 'Anchura en la parte superior y postura' },
    muscles:     { en: ['Shoulders','Traps'],     sq: ['Supet','Trapezoidi'],         es: ['Hombros','Trapecios'] },
  },
  {
    id: 'legs-quads',
    emoji: '🦵',
    color: '#1D8348',
    gradient: 'linear-gradient(135deg, #145A32 0%, #1D8348 100%)',
    icons: ['🦵', '🔥', '⚡', '💪'],
    categories: [{ id: 9, count: 8 }],
    names:       { en: 'Legs — Quad Focus',      sq: 'Këmbët — Fokus Kuadricepsi',  es: 'Piernas — Énfasis en Cuádriceps' },
    descs:       { en: 'Quad-dominant strength and size',     sq: 'Fuqi dhe vëllim i kuadricepsit',          es: 'Fuerza y volumen de cuádriceps' },
    muscles:     { en: ['Quadriceps','Glutes'],   sq: ['Kuadricepsi','Gluteusi'],     es: ['Cuádriceps','Glúteos'] },
  },
  {
    id: 'legs-hamstrings',
    emoji: '🏃',
    color: '#CA6F1E',
    gradient: 'linear-gradient(135deg, #9A4A0E 0%, #CA6F1E 100%)',
    icons: ['🏃', '⚡', '🔥', '💪'],
    categories: [{ id: 9, count: 5 }, { id: 14, count: 3 }],
    names:       { en: 'Legs — Hinge & Calves',  sq: 'Këmbët — Panxha & Viçat',     es: 'Piernas — Bisagra & Pantorrillas' },
    descs:       { en: 'Posterior chain and calf development', sq: 'Zinxhiri i pasëm dhe zhvillimi i viçave', es: 'Cadena posterior y desarrollo de pantorrillas' },
    muscles:     { en: ['Hamstrings','Calves'],   sq: ['Panxhat','Viçat'],            es: ['Isquiotibiales','Pantorrillas'] },
  },
  {
    id: 'arms',
    emoji: '💪',
    color: '#E67E22',
    gradient: 'linear-gradient(135deg, #B7520B 0%, #E67E22 100%)',
    icons: ['💪', '🔥', '⚡', '🦾'],
    categories: [{ id: 8, count: 8 }],
    names:       { en: 'Arms Day',               sq: 'Dita e Krahëve',               es: 'Día de Brazos' },
    descs:       { en: 'Dedicated arm sculpting session',     sq: 'Seancë e dedikuar për krahët',            es: 'Sesión dedicada a los brazos' },
    muscles:     { en: ['Biceps','Triceps'],       sq: ['Bicepsi','Tricepsi'],          es: ['Bíceps','Tríceps'] },
  },
  {
    id: 'core',
    emoji: '🎯',
    color: '#148F77',
    gradient: 'linear-gradient(135deg, #0B6251 0%, #148F77 100%)',
    icons: ['🎯', '⚡', '🔥', '💪'],
    categories: [{ id: 10, count: 8 }],
    names:       { en: 'Core & Abs',             sq: 'Beli & Abdominali',             es: 'Core & Abdominales' },
    descs:       { en: 'Foundation of every movement',        sq: 'Themeli i çdo lëvizjeje',                 es: 'Base de todo movimiento' },
    muscles:     { en: ['Abs','Core'],            sq: ['Abdominali','Beli'],            es: ['Abdominales','Core'] },
  },
];

// Offline fallback exercises (used when API is unreachable)
const FALLBACK = {
  11: [ // Chest
    { id: 9011, names: { en: 'Barbell Bench Press',    es: 'Press de Banca con Barra',      sq: 'Shtytje me Stol me Barre'       }, muscles: 'Pectoralis major', image: null },
    { id: 9012, names: { en: 'Incline Dumbbell Press', es: 'Press Inclinado con Mancuernas', sq: 'Shtytje e Pjerrët me Pesha'     }, muscles: 'Pectoralis major (upper)', image: null },
    { id: 9013, names: { en: 'Dumbbell Flyes',         es: 'Aperturas con Mancuernas',       sq: 'Hapja me Pesha'                 }, muscles: 'Pectoralis major', image: null },
    { id: 9014, names: { en: 'Cable Crossover',        es: 'Cruce de Poleas',                sq: 'Kryqëzim me Kavo'               }, muscles: 'Pectoralis major', image: null },
    { id: 9015, names: { en: 'Push-Ups',               es: 'Flexiones',                      sq: 'Shtytje'                        }, muscles: 'Pectoralis major, Triceps', image: null },
    { id: 9016, names: { en: 'Decline Bench Press',    es: 'Press Declinado',                sq: 'Shtytje e Zbritur me Stol'      }, muscles: 'Pectoralis major (lower)', image: null },
  ],
  12: [ // Back
    { id: 9021, names: { en: 'Barbell Row',            es: 'Remo con Barra',                 sq: 'Remo me Barre'                  }, muscles: 'Latissimus dorsi', image: null },
    { id: 9022, names: { en: 'Pull-Ups',               es: 'Dominadas',                      sq: 'Tërheqje'                       }, muscles: 'Latissimus dorsi, Biceps', image: null },
    { id: 9023, names: { en: 'Seated Cable Row',       es: 'Remo en Polea Baja',             sq: 'Remo i Ulur me Kavo'            }, muscles: 'Rhomboids, Latissimus dorsi', image: null },
    { id: 9024, names: { en: 'Lat Pulldown',           es: 'Jalón al Pecho',                 sq: 'Tërheqje Lat'                   }, muscles: 'Latissimus dorsi', image: null },
    { id: 9025, names: { en: 'Deadlift',               es: 'Peso Muerto',                    sq: 'Ngritja e Rëndë'                }, muscles: 'Erector spinae, Glutes', image: null },
    { id: 9026, names: { en: 'T-Bar Row',              es: 'Remo en T',                      sq: 'Remo T-Bar'                     }, muscles: 'Latissimus dorsi', image: null },
  ],
  13: [ // Shoulders
    { id: 9031, names: { en: 'Barbell Overhead Press', es: 'Press Militar con Barra',        sq: 'Shtytje mbi Kokë me Barre'      }, muscles: 'Deltoid', image: null },
    { id: 9032, names: { en: 'Lateral Raise',          es: 'Elevaciones Laterales',          sq: 'Ngritje Anësore'                }, muscles: 'Deltoid (lateral)', image: null },
    { id: 9033, names: { en: 'Dumbbell Shoulder Press',es: 'Press de Hombros con Mancuernas',sq: 'Shtytje Supesh me Pesha'        }, muscles: 'Deltoid', image: null },
    { id: 9034, names: { en: 'Front Raise',            es: 'Elevaciones Frontales',          sq: 'Ngritje Frontale'               }, muscles: 'Deltoid (anterior)', image: null },
    { id: 9035, names: { en: 'Rear Delt Fly',          es: 'Vuelo de Deltoides Posterior',   sq: 'Hapja e Deltoidit të Pasëm'     }, muscles: 'Deltoid (posterior)', image: null },
    { id: 9036, names: { en: 'Barbell Shrug',          es: 'Encogimiento con Barra',         sq: 'Ngritje Supesh me Barre'        }, muscles: 'Trapezius', image: null },
    { id: 9037, names: { en: 'Arnold Press',           es: 'Press Arnold',                   sq: 'Shtytje Arnold'                 }, muscles: 'Deltoid', image: null },
    { id: 9038, names: { en: 'Upright Row',            es: 'Remo al Mentón',                 sq: 'Remo Vertikal'                  }, muscles: 'Deltoid, Trapezius', image: null },
  ],
  9: [ // Legs
    { id: 9041, names: { en: 'Barbell Squat',          es: 'Sentadilla con Barra',           sq: 'Ulje-Ngritje me Barre'          }, muscles: 'Quadriceps, Glutes', image: null },
    { id: 9042, names: { en: 'Leg Press',              es: 'Prensa de Piernas',              sq: 'Shtytje Këmbësh'                }, muscles: 'Quadriceps, Glutes', image: null },
    { id: 9043, names: { en: 'Romanian Deadlift',      es: 'Peso Muerto Rumano',             sq: 'Ngritje Rumune'                 }, muscles: 'Hamstrings, Glutes', image: null },
    { id: 9044, names: { en: 'Dumbbell Lunge',         es: 'Zancadas con Mancuernas',        sq: 'Hap-Gjuri me Pesha'             }, muscles: 'Quadriceps, Glutes', image: null },
    { id: 9045, names: { en: 'Leg Extension',          es: 'Extensión de Cuádriceps',        sq: 'Shtrirje e Kuadricepsit'        }, muscles: 'Quadriceps', image: null },
    { id: 9046, names: { en: 'Lying Leg Curl',         es: 'Curl Femoral Tumbado',           sq: 'Tkurrje Këmbe të Shtrirë'       }, muscles: 'Hamstrings', image: null },
    { id: 9047, names: { en: 'Bulgarian Split Squat',  es: 'Sentadilla Búlgara',             sq: 'Squat Bullgar'                  }, muscles: 'Quadriceps, Glutes', image: null },
    { id: 9048, names: { en: 'Hack Squat',             es: 'Sentadilla Hack',                sq: 'Squat Hack'                     }, muscles: 'Quadriceps', image: null },
  ],
  14: [ // Calves
    { id: 9051, names: { en: 'Standing Calf Raise',    es: 'Elevación de Talones de Pie',    sq: 'Ngritje Viçi në Këmbë'          }, muscles: 'Gastrocnemius', image: null },
    { id: 9052, names: { en: 'Seated Calf Raise',      es: 'Elevación de Talones Sentado',   sq: 'Ngritje Viçi të Ulur'           }, muscles: 'Soleus', image: null },
    { id: 9053, names: { en: 'Donkey Calf Raise',      es: 'Elevación de Talones Tipo Burro',sq: 'Ngritje Viçi Gomar'             }, muscles: 'Gastrocnemius', image: null },
  ],
  8: [ // Arms
    { id: 9061, names: { en: 'Barbell Curl',           es: 'Curl con Barra',                 sq: 'Tkurrje me Barre'               }, muscles: 'Biceps brachii', image: null },
    { id: 9062, names: { en: 'Hammer Curl',            es: 'Curl Martillo',                  sq: 'Tkurrje Çekiç'                  }, muscles: 'Brachialis, Biceps', image: null },
    { id: 9063, names: { en: 'Preacher Curl',          es: 'Curl en Banco Scott',            sq: 'Tkurrje Scott'                  }, muscles: 'Biceps brachii', image: null },
    { id: 9064, names: { en: 'Tricep Pushdown',        es: 'Extensión de Tríceps en Polea',  sq: 'Shtytje Tricepsi me Kavo'       }, muscles: 'Triceps brachii', image: null },
    { id: 9065, names: { en: 'Skull Crushers',         es: 'Rompe Cráneos',                  sq: 'Shtrirje Tricepsi'              }, muscles: 'Triceps brachii', image: null },
    { id: 9066, names: { en: 'Overhead Tricep Extension', es: 'Extensión de Tríceps sobre la Cabeza', sq: 'Shtrirje Tricepsi mbi Kokë' }, muscles: 'Triceps brachii', image: null },
    { id: 9067, names: { en: 'Dips',                   es: 'Fondos en Paralelas',            sq: 'Ulje-Ngritje në Paralele'       }, muscles: 'Triceps, Chest', image: null },
    { id: 9068, names: { en: 'Close-Grip Bench Press', es: 'Press de Banca Agarre Cerrado',  sq: 'Shtytje me Kapur Ngushtë'       }, muscles: 'Triceps brachii', image: null },
  ],
  10: [ // Abs
    { id: 9071, names: { en: 'Crunch',                 es: 'Crunch Abdominal',               sq: 'Kërthizë'                       }, muscles: 'Rectus abdominis', image: null },
    { id: 9072, names: { en: 'Plank',                  es: 'Plancha',                        sq: 'Pllakë'                         }, muscles: 'Core', image: null },
    { id: 9073, names: { en: 'Hanging Leg Raise',      es: 'Elevación de Piernas Colgado',   sq: 'Ngritje Këmbësh të Varur'       }, muscles: 'Rectus abdominis, Hip flexors', image: null },
    { id: 9074, names: { en: 'Cable Crunch',           es: 'Crunch en Polea',                sq: 'Kërthizë me Kavo'               }, muscles: 'Rectus abdominis', image: null },
    { id: 9075, names: { en: 'Russian Twist',          es: 'Giro Ruso',                      sq: 'Rrotullim Rus'                  }, muscles: 'Obliques', image: null },
    { id: 9076, names: { en: 'Ab Wheel Rollout',       es: 'Rueda Abdominal',                sq: 'Rrota e Abdominalit'            }, muscles: 'Rectus abdominis', image: null },
    { id: 9077, names: { en: 'Bicycle Crunch',         es: 'Crunch de Bicicleta',            sq: 'Kërthizë Biçiklete'             }, muscles: 'Obliques, Rectus abdominis', image: null },
    { id: 9078, names: { en: 'Mountain Climbers',      es: 'Escaladores de Montaña',         sq: 'Ngjitës Mali'                   }, muscles: 'Core, Hip flexors', image: null },
  ],
};
